name: Bedwars
version: 2.2
api: 1.14.0
main: ByBezge\Bedwars
author: ByBezge
website: ://GitHub.com/ByBezge
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
